
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'
import { userAtom } from '@/utils/userAtom'
import { useHydrateAtoms } from 'jotai/utils'
import { ThemeProvider } from '@/components/ui/theme-provider'
import { getUserData } from '@/utils/apis/user'
import { cookies, headers } from 'next/headers'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const userId = cookies().get('user_id');
	const userData = await getUserData(userId?.value ?? '');

	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider attribute='class' defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					<Header userData={userData} />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	)
}
